### ISSUE TITLE
新建模块，需要重启npm run dev

### ISSUE THREAD

**Issue by zchrissirhcz** [jarvan4dev/vue-multi-page#1]
首先注意到每个模块所在的目录`src/module/mymodule/`下面,html文件和js文件必须要和`mymodule`一致，我尝试修改了html或js文件的名字，发现不会热更新上来，页面不会提示有错。

尝试重启了`npm run dev`，此时被改名字的页面无法访问（此时为正常）。

以及，另一种case：当新建一个模块，需要创建`src/anothermodule/`目录，以及相应的html和js文件。此时`npm run dev`脚本同样不能自动更新上来。

哪位对js和webpack比较熟，有空改一个？

**Comment by jarvan4dev** [comment]
描述的有点混乱，但是我还是catch到了一些重点[😄]
1、关于HTML、js文件名必须与module名称一致的问题应该是不存在的，但是之前的时候，每个module下面的HTML和js文件必须不一样，比如说 AModule下面有一个index.html了，其他module就不能有这个文件了，关于这个BUG，我已经改过了

关于自动加载新建模块，我还没有研究，你可以直接提PR

**Comment by luchanan** [comment]
@jarvan4dev 这个重名覆盖问题，具体代码在哪里呢？
