### ISSUE TITLE
生命周期函数不执行

### ISSUE THREAD

**Issue by JasenWu** [jarvan4dev/vue-multi-page#11]
你好，如题，生命周期函数不执行，测了了beforeCreate，created，beforeMounte，mounted，发现只会执行created,其它三个均不执行，请问怎么办？

 
 
 
![image](https://cloud.githubusercontent.com/assets/8563465/23827900/830d167e-06fa-11e7-875a-121ba613b20c.png)

![image](https://cloud.githubusercontent.com/assets/8563465/23821659/81f4bd9a-0674-11e7-802b-4229cc09de99.png)

**Comment by JasenWu** [comment]
自问自答吧，这个是我遇到的vue版本问题，就这个问题我建了个新仓库，地址在：https://github.com/JasenWu/vue2.0-multi-page

**Comment by jarvan4dev** [comment]
@JasenWu 👍
