### ISSUE TITLE
把这个多页面的脚手架升级为2.0呗~

### ISSUE THREAD

**Issue by jankerli** [jarvan4dev/vue-multi-page#7]
@jarvan4dev 什么时候把这个多页面的脚手架升级为2.0版本的呀？
:)

**Comment by jarvan4dev** [comment]
有时间你做下呗，年底公司的事情比较多，而且我是做后端的，这个改造也不是很麻烦，主要是用了一些nodejs的函数，关于这些函数的使用在代码中都有注释的，看看utils.js

**Comment by jarvan4dev** [comment]
@jankerli

**Comment by jarvan4dev** [comment]
其实我目前也在做vue，还是用的1.0，你可以看看懒加载

**Comment by csdudu** [comment]
我初始化了一个vue-cli2.0，然后按你文中所说的修改了那几处，npm run dev还是只能出现根目录下的单页主文件，并不能出现src\module下面的多页面，好苦涩。

**Comment by csdudu** [comment]
是否方便给个邮件地址？我发给你给瞧瞧？

**Comment by youngchen1987** [comment]
https://github.com/youngchen1987/vue2.0-multi-page 已经修改为2.0 目前能运行  但是不知道还有配置的漏缺 @jankerli @jarvan4dev @csdudu

**Comment by jarvan4dev** [comment]
@youngchen1987 非常感谢，一直没时间做，而且我也不觉得必须要这样做，完全可以使用异步加载机制

**Comment by jarvan4dev** [comment]
https://github.com/JasenWu/vue2.0-multi-page
